# Generated by Django 2.0.6 on 2018-06-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'ordering': ('-created',)},
        ),
    ]
